
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    restart: unless-stopped
  backend:
    build: 
      context: .
      dockerfile: ./Orders/Dockerfile
    environment:
      ConnectionStrings__OrdersDatabase: "Host=postgres;Database=ordersApi;Username=postgres;Password=P@ssword"
    ports:
      - "12315:8080"
    networks:
      - backend
    depends_on:
      - postgres
    restart: unless-stopped
  postgres:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_PASSWORD: "P@ssword"
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
      - backend
    restart: unless-stopped


networks:
  backend:

volumes:
  postgres: